language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - make install-dev

env:
    global:
        - SOURCE_FILES=`find ./pymfe/ -name '*.py'`
        - TEST_FILES=./tests/

# Disabled messages in Pylint
#     C0103: Argument name "example" doesn't conform to snake_case naming style
#     R0913: Too many arguments
#     R0902: Too many instance attributes
#     R0914: Too many local variables
#     C0302: Too many lines in module
#     R0904: Too many public methods
#     R0801: Similar lines in "x" files
#     E1101: Module 'patsy' has no 'dmatrix' member (need to be fixed?)
#
script:
    - mypy $SOURCE_FILES --ignore-missing-imports
    - pylint $SOURCE_FILES -d 'C0103, R0913, R0902, R0914, C0302, R0904, R0801, E1101, C0330'
    - pytest tests/ --showlocals -v --cov=pymfe/
    - make html

notifications:
    email:
        on_success: never
        on_failure: never

after_success:
    - bash <(curl -s https://codecov.io/bash)
